spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest1
    username: root
    password: 831143
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: admin.*
      filters: stat,wall,slf4j

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
        config:
          enabled: true


      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 831143
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  redis:
    host: 47.97.82.193
    port: 6379
    password: Qq831143@
    lettuce:
      pool:
        max-active: 10
        min-idle: 5
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
